iterations = 1
name = "frame"

[window]
  background_color = { red = 0, green = 0, blue = 0 }
  height = 3840
  width = 3840

[[spinners]]
  center = [-1000, -1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1

[[spinners]]
  center = [-1000, 0]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1

[[spinners]]
  center = [-1000, 1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1

[[spinners]]
  center = [0, -1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1

[[spinners]]
  center = [0, 0]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1

[[spinners]]
  center = [0, 1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1

[[spinners]]
  center = [1000, -1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1

[[spinners]]
  center = [1000, 0]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1

[[spinners]]
  center = [1000, 1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 450
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 170, green = 128, blue = 255 }
    point_weight = 1
