iterations = 1
name = "frame_phone"

[window]
  background_color = { red = 245, green = 222, blue = 179 }
  height = 3840
  width = 2160

[[spinners]]
  center = [-500, -1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [0, -1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [500, -1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [-500, -500]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [0, -500]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [500, -500]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [-500, 0]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [0, 0]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [500, 0]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [-500, 500]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [0, 500]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [500, 500]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [-500, 1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [0, 1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8

[[spinners]]
  center = [500, 1000]
  density = 1
  density_factor = 0.6
  initial_points = 1000
  radius = 200
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8
