name = "frame"

[window]
  background_color = { red = 245, green = 222, blue = 179 }
  height = 1500
  width = 1500

[[spinners]]
  center = [-400, -400]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.45

[[spinners]]
  center = [-400, 0]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.5

[[spinners]]
  center = [-400, 400]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.5

[[spinners]]
  center = [0, -400]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.5

[[spinners]]
  center = [0, 0]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.5

[[spinners]]
  center = [0, 400]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.5

[[spinners]]
  center = [400, -400]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.5

[[spinners]]
  center = [400, 0]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.5

[[spinners]]
  center = [400, 400]
  density = 1
  density_factor = 0.8
  initial_points = 1000
  radius = 180
  theta_increment = 0.01
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.5
