name = "single"

[window]
  background_color = { red = 245, green = 222, blue = 179 }
  height = 1500
  width = 1500

[[spinners]]
  center = [0, 0]
  density = 1
  density_factor = 0.8
  initial_points = 2000
  radius = 600
  theta_increment = 0.005
  theta_max = 4.17
  [spinners.drawing]
    color = { red = 183, green = 122, blue = 55 }
    point_weight = 0.8
