[package]
  authors = ["Donatien Criaud <donatien.criaud@gmail.com>"]
  edition = "2021"
  name = "travelers"
  version = "0.1.0"

[dependencies]
  display = { path = "../display" }
  nannou = "0.18.1"
  rand = "0.8.5"
